on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: NPM Install
        run: npm ci
      - name: Build Eleventy
        run: npx @11ty/eleventy
      - name: Build Tailwind
        run: npx tailwindcss -i ./src/styles.css -o ./public/styles.css
      - name: Build JS
        run: ./node_modules/.bin/esbuild src/js/app.js --bundle --outfile=public/js/app.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: public
          PUBLISH_BRANCH: master
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}